In [2]:
import numpy as np
import kwant
import PauliMatrices as PM
from math import pi
from cmath import sqrt

In [30]:
a=1;
t=25/a/a;
alpha=5/(2*a);
Delta_0=.2;
mu=0.2;
wireLength=100;
Vz=0;
Gamma=1e-5;Nbarrier=2;Ebarrier=10;

In [7]:
np.warnings.filterwarnings('ignore');
junction=kwant.Builder();
lat=kwant.lattice.chain(a);    

In [12]:
for x in range(wireLength):
            junction[lat(x)]=(-mu+2*t)*PM.tzs0+Delta_0*PM.txs0+Vz*PM.t0sx-1j*Gamma*PM.t0s0;

In [21]:
junction[lat(0)]

array([[ 49.8-1.e-05j,   0. +0.e+00j,   0.2+0.e+00j,   0. +0.e+00j],
       [  0. +0.e+00j,  49.8-1.e-05j,   0. +0.e+00j,   0.2+0.e+00j],
       [  0.2+0.e+00j,   0. +0.e+00j, -49.8-1.e-05j,   0. +0.e+00j],
       [  0. +0.e+00j,   0.2+0.e+00j,   0. +0.e+00j, -49.8-1.e-05j]])

In [25]:
for x in range(1,wireLength):
            junction[lat(x-1),lat(x)]=-t*PM.tzs0-1j*alpha*PM.tzsy;

In [33]:
junction[lat(0)]

array([[ 59.8,   0. ,   0. ,   0. ],
       [  0. ,  59.8,   0. ,   0. ],
       [  0. ,   0. , -59.8,   0. ],
       [  0. ,   0. ,   0. , -59.8]])

In [26]:
junction[lat(0),lat(1)]

array([[-25. +0.j,  -2.5+0.j,  -0. +0.j,  -0. +0.j],
       [  2.5+0.j, -25. +0.j,  -0. +0.j,  -0. +0.j],
       [ -0. +0.j,  -0. +0.j,  25. +0.j,   2.5+0.j],
       [ -0. +0.j,  -0. +0.j,  -2.5+0.j,  25. +0.j]])

In [31]:
for x in range(Nbarrier):
            junction[ lat(x) ] = (2*t - mu + Ebarrier)*PM.tzs0 + Vz*PM.t0sx;